export const GET_DASHBOARD_ISSUE_OPEN = "GET_DASHBOARD_ISSUE_OPEN";
export const GET_DASHBOARD_ISSUE_PROGRESS = "GET_DASHBOARD_ISSUE_PROGRESS";
export const GET_DASHBOARD_ISSUE_DONE = "GET_DASHBOARD_ISSUE_DONE";
export const GET_ISSUE_DETAILS = "GET_ISSUE_DETAILS";
